version: "3"
services:
  web:
    image: nginx
  tor:
    image: osminogin/tor-simple
    volumes:
      - ./torrc:/etc/tor/torrc:ro
      - tor-data-directory:/var/lib/tor
    depends_on:
      - web
volumes:
  tor-data-directory:
